# Generated by Django 3.2.9 on 2022-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('streams_total', models.CharField(blank=True, max_length=10, null=True)),
                ('popularity_current', models.CharField(blank=True, max_length=10, null=True)),
                ('followers_total', models.CharField(blank=True, max_length=10, null=True)),
                ('playlists_total', models.CharField(blank=True, max_length=10, null=True)),
                ('image_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
