# Generated by Django 3.2.9 on 2022-02-08 09:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artistdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistdata',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
