# Generated by Django 3.2.9 on 2022-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220208_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistdata',
            name='name',
            field=models.CharField(max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='stats',
            field=models.CharField(max_length=10255),
        ),
    ]
