# Generated by Django 3.2.9 on 2022-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220208_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistdata',
            name='stats',
        ),
        migrations.AddField(
            model_name='artistdata',
            name='applemusic',
            field=models.CharField(max_length=10255, null=True),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='spotify',
            field=models.CharField(max_length=10255, null=True),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='tiktok',
            field=models.CharField(max_length=10255, null=True),
        ),
        migrations.AddField(
            model_name='artistdata',
            name='youtube',
            field=models.CharField(max_length=10255, null=True),
        ),
    ]
