# Generated by Django 3.2.9 on 2022-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220209_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistdata',
            old_name='applemusic',
            new_name='stats',
        ),
        migrations.RemoveField(
            model_name='artistdata',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='artistdata',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='artistdata',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='artistdata',
            name='image',
            field=models.CharField(max_length=1255, null=True),
        ),
    ]
